### PR TITLE
Extended TypeScript support

### PR DESCRIPTION
**Pull request by malj**
Extended TypeScript support which provides optional event typing and fixes some minor issues:

- full type support for string event names, including listener argument types
- partial type support for "*": available event names are typed, but listener's `data` argument type can't be inferred accurately in TypeScript yet (https://github.com/microsoft/TypeScript/issues/13995)
- basic type support for symbol event names: symbols can't be narrowed down to literal types nor used as indexers in TypeScript (https://github.com/Microsoft/TypeScript/issues/1863)
- changed private properties' access level to protected to enable access when inheriting, in case anyone wanted to expand Nanobus functionality
- added typed `_emit()` method
- fixed `_starListeners` property name typo

```ts
type Events = {
    a: (n: number) => void
    b: (n: number, s: string) => void
}

const emitter = new Nanobus<Events>()

emitter.emit("a", 0) // required arguments: [number]
emitter.on("a", n => {
    // n: number
})

emitter.emit("b", 0, "") // required arguments: [number, string]
emitter.on("b", (n, s) => {
    // n: number
    // s: string
})

const symbol = Symbol()
emitter.emit(symbol)  // arguments: any[]
emitter.on(symbol, (...args) => {
    // args: any[]
})

emitter.on("*", (eventName, data, uuid) => {
    // eventName: "a" | "b" | symbol
    // data: any[]
    // uuid: string | undefined
})
```

### CODE REVIEW

**Comment by malj** [comment]
Just noticed the [other pull request](https://github.com/choojs/nanobus/pull/40), I apologize for skipping it. I went over its code, this is the same concept with additional symbol names and inheritance support, and fixed `removeAllListeners()` method signature. Is there a reason why it wasn't merged back in October?

**Comment by Tyler-Murphy** [comment]
I wrote that other pull request. I forgot about it. I don't think there was a good reason not to merge it, other than support for symbols.

This looks great! I'll close my PR in favor of this one.

With https://github.com/microsoft/TypeScript/pull/38234, which is in the Typescript 4.0 beta, it might be possible to replace the values in `type Events` with tuples, but I haven't looked into it, and depending how soon it's out of beta, it might not be worth waiting.

**Comment by malj** [comment]
Hi @Tyler-Murphy, thanks for the update. I apologize again for missing your PR, I would have forked and updated it if I had noticed it earlier.
Using tuples is possible since TypeScript 3.0 even without named members from the PR you linked. I had considered using them for the `Events` config type instead of function signatures, but decided in favor of the more explicit API.

**Review by goto-bus-stop — APPROVED** [review]
lgtm, thank you both for the PRs 😊

**Comment by goto-bus-stop** [comment]
📦 4.5.0

**Pull request merged**
